version: '2'
services:
  mongodb:
    ports:
      - 27017:27017/tcp
    environment:
    - MONGO_ADMIN_PASSWORD=admin
    - MONGO_USERNAME_1=localUser
    - MONGO_PASSWORD_1=local
    - MONGO_DATABASE_1=hollywood-it
    - MONGO_ROLE_1=readWrite
    image: docker-test.pibenchmark.com/pi-mongo:3.2
